spring:
  datasource:
    url: jdbc:mysql://spring.ckxxxsfzfyty.us-east-1.rds.amazonaws.com/eazyschool
    username: admin
    password: admin123
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
